const mockDocuments = [
  {
    id: 1,
    title: "Software Engineering Syllabus",
    name: "Software Engineering Syllabus",
    type: "pdf",
    size: "1.2 MB",
    url: "/mock-docs/software-engineering.pdf",
    downloadUrl: "/mock-docs/software-engineering.pdf",
    year: "2024",
    degree: "bachelor",
    department: "Computer Science",
    semester: "first",
    totalPages: 5,
    rating: 4,
    liked: false,
    category: "Syllabus",
    status: "Approved",
    uploadedBy: { name: "Alice Johnson" },
    uploadDate: "2024-01-11T10:00:00Z",
    fileName: "software-engineering.pdf",
    fileSize: "1.2 MB"
  },
  {
    id: 2,
    title: "Database Project Report",
    name: "Database Project Report",
    type: "pdf",
    size: "2.5 MB",
    url: "/mock-docs/database-project.pdf",
    downloadUrl: "/mock-docs/database-project.pdf",
    year: "2023",
    degree: "masters",
    department: "Information Technology",
    semester: "second",
    totalPages: 5,
    rating: 5,
    liked: true,
    category: "Project",
    status: "Need Approval",
    uploadedBy: { name: "Bob Smith" },
    uploadDate: "2023-12-15T09:30:00Z",
    fileName: "database-project.pdf",
    fileSize: "2.5 MB"
  },
  {
    id: 3,
    title: "Engineering Drawing Notes",
    name: "Engineering Drawing Notes",
    type: "pdf",
    size: "900 KB",
    url: "/mock-docs/engineering-drawing.pdf",
    downloadUrl: "/mock-docs/engineering-drawing.pdf",
    year: "2022",
    degree: "diploma",
    department: "Engineering",
    semester: "first",
    totalPages: 5,
    rating: 3,
    liked: false,
    category: "Notes",
    status: "Approved",
    uploadedBy: { name: "Carol Lee" },
    uploadDate: "2022-09-21T14:20:00Z",
    fileName: "engineering-drawing.pdf",
    fileSize: "900 KB"
  },
  {
    id: 4,
    title: "IT Security Guidelines",
    name: "IT Security Guidelines",
    type: "pdf",
    size: "1.8 MB",
    url: "/mock-docs/it-security.pdf",
    downloadUrl: "/mock-docs/it-security.pdf",
    year: "2024",
    degree: "bachelor",
    department: "Information Technology",
    semester: "second",
    totalPages: 5,
    rating: 2,
    liked: false,
    category: "Guidelines",
    status: "Need Approval",
    uploadedBy: { name: "David Kim" },
    uploadDate: "2024-02-05T11:45:00Z",
    fileName: "it-security.pdf",
    fileSize: "1.8 MB"
  },
  {
    id: 5,
    title: "Computer Networks Lab Manual",
    name: "Computer Networks Lab Manual",
    type: "pdf",
    size: "3.1 MB",
    url: "/mock-docs/networks-lab-manual.pdf",
    downloadUrl: "/mock-docs/networks-lab-manual.pdf",
    year: "2023",
    degree: "bachelor",
    department: "Computer Science",
    semester: "first",
    totalPages: 5,
    rating: 5,
    liked: true,
    category: "Lab Manual",
    status: "Approved",
    uploadedBy: { name: "Eve Turner" },
    uploadDate: "2023-11-10T08:10:00Z",
    fileName: "networks-lab-manual.pdf",
    fileSize: "3.1 MB"
  }
];

export default mockDocuments;